### ISSUE TITLE
The example with React do not work.

### ISSUE THREAD

**Issue by lauterry** [krasimir/coloor-loader#1]
Hello

The example folder with React do not work.

Could you make the example work please ?

Best regards

**Comment by krasimir** [comment]
Yep, let me check later today.

**Comment by krasimir** [comment]
I just tried locally and it seems that the example is working. What I did is:

``` shell
cd example
npm i
webpack
```

The result was 
![image](https://cloud.githubusercontent.com/assets/528677/14482540/9030185c-0146-11e6-82c6-358aa64a6e94.png)

And I see the decorated jsx statements in `dist/bundle.js`
![image](https://cloud.githubusercontent.com/assets/528677/14482550/a9903836-0146-11e6-8e7e-f93b0c249610.png)

What was missing is a page that shows the produced bundle in action. It is now in place under `example/index.html`.

P.S.
A new version `0.1.3` is released.
